# Generated by Django 4.2.30 on 2026-06-06 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('letter_grade', models.CharField(default='', max_length=5)),
                ('github_health', models.CharField(default='', max_length=20)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('first_impression', models.TextField(default='')),
                ('recruiter_score', models.IntegerField(default=0)),
                ('recruiter_sentiment', models.CharField(default='', max_length=20)),
                ('recruiter_signals', models.JSONField(default=list)),
                ('recruiter_timeline', models.JSONField(default=list)),
                ('detected_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('security_issues', models.JSONField(default=list)),
                ('documentation_checks', models.JSONField(default=list)),
                ('production_checks', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('roasts', models.JSONField(default=list)),
                ('benchmarks', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField()),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('last_updated', models.CharField(default='', max_length=30)),
                ('scores', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='analysis.analysisreport')),
            ],
        ),
    ]
