# Generated by Django 4.2.30 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='current_step',
            field=models.CharField(default='Fetching GitHub repositories...', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='file_tree_definitions',
            field=models.JSONField(default=list),
        ),
    ]
