# Generated by Django 4.2.30 on 2026-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisreport_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='github_profile',
            field=models.JSONField(default=dict),
        ),
    ]
